services:
  db:
    image: postgres:15-alpine
    container_name: container-test-sps-db
    environment:
      POSTGRES_DB: test-sps-db
      POSTGRES_USER: test-sps-user
      POSTGRES_PASSWORD: test-sps-password
    ports:
      - "5432:5432"
    volumes:
      - test-sps-volume:/var/lib/postgresql/data

volumes:
  test-sps-volume:

